[[redirects]]
    from = "https://gallery-lesterong.netlify.app/*"
    to = "https://gallery.lesterong.com/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200